### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by javens0601** [Shimada666/v-code-diff#57]
vue-router.js:2320 TypeError: Object(...) is not a function
    at eval (index.es.js?7843:4815:1)
    at ./node_modules/v-code-diff/dist/index.es.js (vendors~man.c05eab8ab2e7570697ab.js:68:1)
    at __webpack_require__ (app.c05eab8ab2e7570697ab.js:833:30)
    at fn (app.c05eab8ab2e7570697ab.js:130:20)
    at eval (cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/ntw/certificateList.vue?vue&type=script&lang=js&:22:70)
    at ./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/ntw/certificateList.vue?vue&type=script&lang=js& (man.c05eab8ab2e7570697ab.js:83:1)
    at __webpack_require__ (app.c05eab8ab2e7570697ab.js:833:30)
    at fn (app.c05eab8ab2e7570697ab.js:130:20)
    at eval (certificateList.vue?a9cc:1:1)
    at ./src/views/ntw/certificateList.vue?vue&type=script&lang=js& (man.c05eab8ab2e7570697ab.js:973:1)

**Comment by javens0601** [comment]
有人解决这个问题了吗？

**Comment by javens0601** [comment]
![image](https://user-images.githubusercontent.com/19501000/222424334-1fceabdc-d962-42d1-bd60-dc924dbbdb3f.png)

**Comment by Shimada666** [comment]
没见过这个问题。你可以提供一个最小的复现仓库么？

**Comment by Mitsuizzz** [comment]
同样出现这个问题，前端刚入门。。
yarn add v-code-diff
然后再main.js中添加了
import CodeDiff from 'v-code-diff'
Vue.use(CodeDiff);

页面代码块
<code-diff
                    :old-string="123"
                    :new-string="2134"
                    output-format="side-by-side"/>

页面控制台
<img width="616" alt="image" src="https://user-images.githubusercontent.com/62683203/224880114-64b253d8-15a4-4dbb-815c-beb188231603.png">

**Comment by Shimada666** [comment]
> 同样出现这个问题，前端刚入门。。 yarn add v-code-diff 然后再main.ts中添加了 import CodeDiff from 'v-code-diff' Vue.use(CodeDiff);
> 
> 页面代码块 `<code-diff :old-string="123" :new-string="2134" output-format="side-by-side"/>`
> 
> 页面控制台 <img alt="image" width="616" src="https://user-images.githubusercontent.com/62683203/224880114-64b253d8-15a4-4dbb-815c-beb188231603.png">

你可以提供一个最小的复现仓库么？

**Comment by Mitsuizzz** [comment]
> > 同样出现这个问题，前端刚入门。。 yarn add v-code-diff 然后再main.ts中添加了 import CodeDiff from 'v-code-diff' Vue.use(CodeDiff);
> > 页面代码块 `<code-diff :old-string="123" :new-string="2134" output-format="side-by-side"/>`
> > 页面控制台 <img alt="image" width="616" src="https://user-images.githubusercontent.com/62683203/224880114-64b253d8-15a4-4dbb-815c-beb188231603.png">
> 
> 你可以提供一个最小的复现仓库么？

很遗憾我是个做后端的，前端初学者，不是个人的仓库，没办法提供

**Comment by Perferson** [comment]
同问 本地不会出问题 ，打包到线上就出现这个问题

**Comment by Shimada666** [comment]
> 同问 本地不会出问题 ，打包到线上就出现这个问题

可以提供一个最小可复现仓库么？
像 #63 一样提供了一个最小可复现仓库，于是我修复了他们那个问题。

**Comment by Shimada666** [comment]
> > 同问 本地不会出问题 ，打包到线上就出现这个问题
> 
> 要看一下你开发环境和生产环境的vue版本是否不一致. 如果不一致,最简单的办法就是锁死vue的版本

确实，上次帮人看了下，配置有问题，配置的 vue 和 vue-template-compiler 的版本不一致，配的一个是 ^2.6.10，一个是 ^2.5.10，最后插件识别到安装的是 vue2.7 的版本，释放了 2.7 对应的编译文件，但实际上用的好像又不是。最后我把 package.json  的 vue 和  vue-template-compiler  版本均改成  ~2.6.14 ，重新安装解决了

**Comment by Shimada666** [comment]
关于这个问题，一个很可能的原因是版本错乱，你用的是 vue2.6 的环境，但是我释放了 2.7 的编译文件。
这块我没有细查，现在提供一个可能的解决方案：

遇到这个问题的用户，一般都是 vue <= 2.6 版本的用户。在 package.json 中，把 vue 和 vue-template-compiler 的版本都改成 "~2.6.14"，再删除你的包管理器的 lock 文件，重新安装，应该可以解决问题。

原理是因为，vue2.6 和 2.7 实际上是有一些不兼容的，配置 vue: ^2.6.14，实际上装的可能是 vue2.7。所以版本改成 ~2.6.14 后，可以将版本锁死在 2.6，解决这个问题

**Comment by wusfe** [comment]
> 关于这个问题，一个很可能的原因是版本错乱，你用的是 vue2.6 的环境，但是我释放了 2.7 的编译文件。 这块我没有细查，现在提供一个可能的解决方案：
> 
> 遇到这个问题的用户，一般都是 vue <= 2.6 版本的用户。在 package.json 中，把 vue 和 vue-template-compiler 的版本都改成 "~2.6.14"，再删除你的包管理器的 lock 文件，重新安装，应该可以解决问题。
> 
> 原理是因为，vue2.6 和 2.7 实际上是有一些不兼容的，配置 vue: ^2.6.14，实际上装的可能是 vue2.7。所以版本改成 ~2.6.14 后，可以将版本锁死在 2.6，解决这个问题

> 我觉得版本错乱是根本原因，但是环境不同造成vue版本不一致的情况需要大家来反馈
> 比如我遇到的为什么开发和生产的vue版本不一样，是因为我生产是走的cdn形式的vue，这个cdn的vue版本是不受pkg文件或pck-lock文件的影响

**Comment by wusfe** [comment]
> 关于这个问题，一个很可能的原因是版本错乱，你用的是 vue2.6 的环境，但是我释放了 2.7 的编译文件。 这块我没有细查，现在提供一个可能的解决方案：
> 
> 遇到这个问题的用户，一般都是 vue <= 2.6 版本的用户。在 package.json 中，把 vue 和 vue-template-compiler 的版本都改成 "~2.6.14"，再删除你的包管理器的 lock 文件，重新安装，应该可以解决问题。
> 
> 原理是因为，vue2.6 和 2.7 实际上是有一些不兼容的，配置 vue: ^2.6.14，实际上装的可能是 vue2.7。所以版本改成 ~2.6.14 后，可以将版本锁死在 2.6，解决这个问题

我觉得版本错乱是根本原因，但是环境不同造成vue版本不一致的情况需要大家来反馈
比如我遇到的为什么开发和生产的vue版本不一样，是因为我生产是走的cdn形式的vue，这个cdn的vue版本是不受pkg文件或pck-lock文件的影响
