### ISSUE TITLE
下载都下载不了...

### ISSUE THREAD

**Issue by YangHaHabiu** [Shimada666/v-code-diff#72]
> vue-demi@0.14.5 postinstall /path/client/node_modules/vue-demi
> node ./scripts/postinstall.js

internal/fs/utils.js:307
    throw err;
    ^

Error: EACCES: permission denied, open '/path/client/node_modules/vue-demi/lib/index.cjs'
    at Object.openSync (fs.js:476:3)
    at Object.writeFileSync (fs.js:1467:35)
    at copy (/path/client/node_modules/vue-demi/scripts/utils.js:24:6)
    at switchVersion (/path/client/node_modules/vue-demi/scripts/utils.js:52:3)
    at Object.<anonymous> (/path/client/node_modules/vue-demi/scripts/postinstall.js:12:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/path/client/node_modules/vue-demi/lib/index.cjs'
}

**Comment by Shimada666** [comment]
很明显的权限问题，你的 node_modules 具有你当前程序不能操作的权限
建议把 node_modules 删除后重装，或者使用 sudo npm install

**Comment by YangHaHabiu** [comment]
我使用的是root用户

**Comment by Shimada666** [comment]
那请你提供一个可复现的最小仓库

**Comment by YangHaHabiu** [comment]
应该是使用了vue-demi包引起的,我现在直接安装vue-demi也是报这个错

**Comment by YangHaHabiu** [comment]
我在win上已经成功安装了打包也成功了,查看页面时报Failed to mount component: template or render function not defined.
